version: '3.6'
services:
  getground_app:
    container_name: getground_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - getground_tempstore
    ports:
      - "3000:3000"
    env_file:
      - ./docker.env
    networks:
      - getground_connect



  getground_tempstore:
    container_name: getground_tempstore
    hostname: redis
    image: redis:alpine
    ports:
      - "6379"
    command: redis-server --requirepass testest
    volumes:
      - redisdata:/data
    networks:
      - getground_connect

volumes:
  redisdata:

networks:
  getground_connect:
